/**
 * VerifIQ — prompt loader.
 *
 * Loads agent system prompts from the canonical files in `verifiq-prompts/` and
 * assembles the layered system prompt: master (file 01) + discipline (file 04 /
 * 07) + self-check (file 13). Prompts are NEVER inlined in source (CLAUDE.md
 * anti-pattern).
 *
 * The loader reads through a `PromptSource` so the same agents run both locally
 * (FsPromptSource — node:fs) and inside a Convex `"use node"` action, which
 * cannot read arbitrary repo files (RecordPromptSource — a bundle generated by
 * scripts/bundle-prompts.mjs). This is the Phase 5 prompt-bundling unblock.
 *
 * Version: 0.8.0-phase5
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";

const MASTER_FILE = "01_master_system_prompt.md";
const DISCIPLINE_FILE = "04_agent_prompts.md";
const COUNCIL_FILE = "07_council_prompts.md";
const SELF_CHECK_FILE = "13_agent_self_check_protocol.md";

/** Default prompts directory: `<cwd>/verifiq-prompts`. */
function defaultPromptsDir(): string {
  const cwd = (globalThis as { process?: { cwd(): string } }).process?.cwd() ?? ".";
  return join(cwd, "verifiq-prompts");
}

/** A source of raw prompt-file contents by filename. */
export interface PromptSource {
  read(file: string): Promise<string>;
}

/** Reads prompt files from disk (local dev / Node tooling). */
export class FsPromptSource implements PromptSource {
  constructor(private readonly dir: string = defaultPromptsDir()) {}
  read(file: string): Promise<string> {
    return readFile(join(this.dir, file), "utf8");
  }
}

/**
 * Reads prompt files from an in-memory bundle (the Convex runtime, which cannot
 * touch the filesystem). Construct from the generated `PROMPT_BUNDLE`.
 */
export class RecordPromptSource implements PromptSource {
  constructor(private readonly files: Record<string, string>) {}
  async read(file: string): Promise<string> {
    const text = this.files[file];
    if (text === undefined) {
      throw new Error(`Prompt file not in bundle: ${file} (regenerate with bundle:prompts)`);
    }
    return text;
  }
}

/**
 * Extract a numbered section (e.g. "04.1", "07.3") delimited by level-2 markdown
 * headings ("## 04.1 · ..."), up to the next level-2 heading.
 */
export function extractSection(markdown: string, sectionId: string): string {
  const lines = markdown.split("\n");
  const startIdx = lines.findIndex((l) => l.startsWith("## ") && l.includes(sectionId));
  if (startIdx === -1) {
    throw new Error(`Prompt section "${sectionId}" not found`);
  }
  const rest = lines.slice(startIdx + 1);
  const endRel = rest.findIndex((l) => l.startsWith("## "));
  return (endRel === -1 ? rest : rest.slice(0, endRel)).join("\n").trim();
}

/** Loads and caches prompt fragments from a PromptSource. */
export class PromptLoader {
  private cache = new Map<string, string>();
  private source: PromptSource;

  /** Accepts a PromptSource, a prompts directory string, or nothing (fs default). */
  constructor(source?: PromptSource | string) {
    this.source =
      typeof source === "string"
        ? new FsPromptSource(source)
        : (source ?? new FsPromptSource());
  }

  private async readCached(file: string): Promise<string> {
    const hit = this.cache.get(file);
    if (hit !== undefined) return hit;
    const text = await this.source.read(file);
    this.cache.set(file, text);
    return text;
  }

  /** The master system prompt (file 01). */
  master(): Promise<string> {
    return this.readCached(MASTER_FILE);
  }

  /** The universal 7-check self-check protocol (file 13). */
  selfCheck(): Promise<string> {
    return this.readCached(SELF_CHECK_FILE);
  }

  /** A discipline prompt section from file 04 (e.g. "04.1" for Architect). */
  async disciplineSection(sectionId: string): Promise<string> {
    return extractSection(await this.readCached(DISCIPLINE_FILE), sectionId);
  }

  /** A council prompt section from file 07 (e.g. "07.3" for the Chair). */
  async councilSection(sectionId: string): Promise<string> {
    return extractSection(await this.readCached(COUNCIL_FILE), sectionId);
  }
}
